version: 2
jobs:
  build:
    docker:
      - image: circleci/node:11.1.0
        environment:
          DB_HOST: localhost
          DB_USER: starter
          DB_PASS: starter
          DB_NAME: starter
          DB_MIN_POOL: 2
          DB_MAX_POOL: 10
          DB_PORT: 5432
          SECRET: test
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_DB: starter
          POSTGRES_PASSWORD: starter
          POSTGRES_USER: starter

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run:
          name: Install dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Run the tests
          command: npm run test
      - run:
          name: Run eslint
          command: npm run eslint

      - store_artifacts:
          path: coverage
          prefix: coverage
  deploy:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
